package com.yykj.system.socket.socketserv4local;

public class DevStateInsert {
	public static void main(String[]args){
		String strs="	ZT_INVOICE	@	0	@	正常有纸	@	发票打印机	#	"
				+"	ZT_INVOICE	@	1	@	告警纸将尽	@	发票打印机	#	"
				+"	ZT_INVOICE	@	2	@	无纸，缺纸	@	发票打印机	#	"
				+"	ZT_INVOICE	@	3	@	堵纸(卡纸)	@	发票打印机	#	"
				+"	ZT_INVOICE	@	4	@	脱机，机械故障	@	发票打印机	#	"
				+"	ZT_INVOICE	@	5	@	脱机，切刀故障	@	发票打印机	#	"
				+"	ZT_INVOICE	@	6	@	打印头过温	@	发票打印机	#	"
				+"	ZT_INVOICE	@	7	@	打印机抬起	@	发票打印机	#	"
				+"	ZT_INVOICE	@	8	@	黑标定位错误	@	发票打印机	#	"
				+"	ZT_INVOICE	@	-1	@	串口被用	@	发票打印机	#	"
				+"	ZT_INVOICE	@	-2	@	超时	@	发票打印机	#	"
				+"	ZT_INVOICE	@	-3	@	发送失败	@	发票打印机	#	"
				+"	ZT_INVOICE	@	-4	@	接收失败	@	发票打印机	#	"
				+"	ZT_INVOICE	@	-5	@	参数错误	@	发票打印机	#	"
				+"	ZT_INVOICE	@	-6	@	掉电	@	发票打印机	#	"
				+"	ZT_INVOICE	@	-7	@	拔掉串口线	@	发票打印机	#	"
				+"	ZT_INVOICE	@	-8	@	接收数据错误	@	发票打印机	#	"
				+"	ZT_RECEIPT	@	0	@	正常有纸	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	1	@	告警纸将尽	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	2	@	无纸，缺纸	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	3	@	堵纸(卡纸)	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	4	@	脱机，机械故障	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	5	@	脱机，切刀故障	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	6	@	打印头过温	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	7	@	打印机抬起	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	8	@	黑标定位错误	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	-1	@	串口被用	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	-2	@	超时	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	-3	@	发送失败	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	-4	@	接收失败	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	-5	@	参数错误	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	-6	@	掉电	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	-7	@	拔掉串口线	@	凭条打印机	#	"
				+"	ZT_RECEIPT	@	-8	@	接收数据错误	@	凭条打印机	#	"
				+"	ZT_EPP	@	0	@	正常	@	加密键盘	#	"
				+"	ZT_EPP	@	-1	@	串口被用,或没有打开	@	加密键盘	#	"
				+"	ZT_EPP	@	-2	@	超时	@	加密键盘	#	"
				+"	ZT_EPP	@	-3	@	发送失败	@	加密键盘	#	"
				+"	ZT_EPP	@	-4	@	接收失败	@	加密键盘	#	"
				+"	ZT_EPP	@	-5	@	参数错误	@	加密键盘	#	"
				+"	ZT_EPP	@	-6	@	掉电	@	加密键盘	#	"
				+"	ZT_EPP	@	-7	@	拔掉串口线	@	加密键盘	#	"
				+"	ZT_EPP	@	-20	@	非法字符	@	加密键盘	#	"
				+"	ZT_EPP	@	1	@	命令可执行,主密钥无效	@	加密键盘	#	"
				+"	ZT_EPP	@	2	@	命令无效,主密钥无效	@	加密键盘	#	"
				+"	ZT_EPP	@	3	@	命令无效,电池可能损坏 	@	加密键盘	#	"
				+"	ZT_EPP	@	4	@	无效命令	@	加密键盘	#	"
				+"	ZT_EPP	@	5	@	CPU错	@	加密键盘	#	"
				+"	ZT_EPP	@	6	@	SRAM错	@	加密键盘	#	"
				+"	ZT_EPP	@	7	@	键盘有短路	@	加密键盘	#	"
				+"	ZT_EPP	@	8	@	串口电平错	@	加密键盘	#	"
				+"	ZT_EPP	@	9	@	CPU卡失效	@	加密键盘	#	"
				+"	ZT_EPP	@	10	@	电池可能损坏	@	加密键盘	#	"
				+"	ZT_EPP	@	11	@	主密钥失效	@	加密键盘	#	"
				+"	ZT_EPP	@	12	@	杂项错	@	加密键盘	#	"
				+"	ZT_EPP	@	13	@	未支持参数	@	加密键盘	#	"
				+"	ZT_IS4215	@	0	@	正常	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	1	@	接收数据为空	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	-1	@	串口被用	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	-2	@	超时	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	-3	@	发送失败	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	-4	@	接收失败	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	-5	@	参数错误	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	-6	@	掉电	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	-7	@	拔掉串口线	@	条码描扫仪	#	"
				+"	ZT_IS4215	@	-8	@	接收数据不正确	@	条码描扫仪	#	"
				+"	ZT_ID	@	0	@	正常	@	身份证读卡器	#	"
				+"	ZT_ID	@	-1	@	加载驱动库失败	@	身份证读卡器	#	"
				+"	ZT_ID	@	-2	@	设备故障	@	身份证读卡器	#	"
				+"	ZT_ID	@	-3	@	检查二代证错误	@	身份证读卡器	#	"
				+"	ZT_ID	@	-4	@	读二代证信息失败	@	身份证读卡器	#	"
				+"	ZT_ID	@	-5	@	串口通信失败	@	身份证读卡器	#	"
				+"	ZT_ID	@	-6	@	寻卡失败	@	身份证读卡器	#	"
				+"	ZT_ID	@	-7	@	初始化失败	@	身份证读卡器	#	"
				+"	ZT_IDC	@	0	@	正常	@	银行卡读卡器	#	"
				+"	ZT_IDC	@	-1	@	设备故障	@	银行卡读卡器		#"
				+"	NETWORK	@	0	@	网络连接正常	@	网络	#	"
				+"	NETWORK	@	1	@	网络连接中断	@	网络	#	"
				+"	SOFTWARE	@	0	@	终端软件开启正常	@	软件	#	"
				+"	SOFTWARE	@	1	@	终端软件开启失败	@	软件		"

;
		
		String [] devs = strs.split("#");
		for (String dev : devs) {
			String [] parames = dev.split("@");
			String sql="insert into DEV_STATE_CODE values(SEQ_DEV_STATE_CODE.nextval,'"+parames[0].trim()+"','"+parames[3].trim()+"','"+parames[1].trim()+"','"+parames[2].trim()+"','"+parames[0].trim()+"_"+parames[1].trim()+"');";
			System.out.println(sql);
		}
	}

}
